[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=38.0.0",
    "pandas>=2.3.3",
    "psycopg2>=2.9.11",
]
